version: '3'
services:
  student-service:
    image: student-service
    build:
      context: ./student-service
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    depends_on:
      - mysql
      - service-registry
      - config-server

  grade-service:
    image: grade-service
    build:
      context: ./grade-service
    ports:
      - "8082:8082"
    networks:
      - microservices-network
    depends_on:
      - mongodb
      - EurekaServer
      - config-server

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_db
    ports:
      - "3306:3306"
    networks:
      - microservices-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - microservices-network

  EurekaServer:
    image: EurekaServer
    build:
      context: ./EurekaServer
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  config-server:
    image: config-server
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    networks:
      - microservices-network
    depends_on:
      - service-registry

  gateway:
    image: gateway
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    environment:
      CONFIG_SERVER_USR: your_config_server_username
      CONFIG_SERVER_PWD: your_config_server_password
    networks:
      - microservices-network
    depends_on:
      - service-registry
      - config-server

networks:
  microservices-network:
    driver: bridge
